[project]
name = "tarefa1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13.1"
dependencies = [
    "pyqt5>=5.15.11",
    "pyqtwebengine>=5.15.7",
    "pyvis>=0.3.2",
    "rich>=13.9.4",
]
